name: Generate OIDC Token

on:
  workflow_dispatch:  # Allows manual triggering

permissions:
  id-token: write  # Required for OIDC token generation
  contents: read

jobs:
  get-token:
    runs-on: ubuntu-latest
    steps:
      - name: Get OIDC Token
        id: get_token
        uses: actions/github-script@v6
        with:
          script: |
            const token = await core.getIDToken('sts.amazonaws.com');
            core.setSecret(token);
            core.setOutput('token', token);

      - name: Display Token Info
        run: |
          echo "Your OIDC token has been generated"
          echo "TOKEN_AVAILABLE=true" >> $GITHUB_ENV

      - name: Save token to file
        run: |
          echo "${{ steps.get_token.outputs.token }}" > token.txt

      - name: Upload token file
        uses: actions/upload-artifact@v3
        with:
          name: oidc-token
          path: token.txt
          retention-days: 1